before_script :
- apt-get update

test3.7:
  image : openjdk
  script:
  - wget https://downloads.sourceforge.net/project/sablecc/SableCC/3.7/sablecc-3.7.zip
  - unzip sablecc-3.7.zip
  - java -jar sablecc-3.7/lib/sablecc.jar objectmacro.sablecc
