before_script:
- apt-get update

stages:
  - build
  - test

build:3.7:
  stage: build
  image: openjdk
  script:
    - wget https://downloads.sourceforge.net/project/sablecc/SableCC/3.7/sablecc-3.7.zip
    - unzip sablecc-3.7.zip
    - java -jar sablecc-3.7/lib/sablecc.jar grammars/objectmacro.sablecc
    - java -jar sablecc-3.7/lib/sablecc.jar grammars/objectmacro.intermediate.sablecc
  artifacts:
    paths:
      - binaries/


test_wih_examples 3.7:
  stage: test
  image: openjdk
  script:
    - javac -sourcepath src src/org/sablecc/ObjectMacro.java
    - cd src
    - java -cp . org.sablecc.ObjectMacro ../example2.objectmacro
  dependencies :
    - build:3.7
